# global.conf for local network exception
servers {
    trusted_proxies static 10.9.9.254/32

}

# Отключаем OCSP stapling - внутренние сертификаты (.home/.lan) не имеют OCSP сервера
ocsp_stapling off